name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Build
      run: go build -o urls-cli

    - name: Create Tag
      id: tag
      run: |
        GIT_TAG=v0.0.$(date +'%Y%m%d%H%M%S')
        echo $GIT_TAG > tag_name.txt
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag $GIT_TAG
        git push origin $GIT_TAG
        echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to Releases
      uses: softprops/action-gh-release@v1
      with:
        files: urls-cli
        tag_name: ${{ env.GIT_TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
